permalink: /:year/:month/:day/:title.html
course_url: "http://www.schulichnotes.com"
course_name: "Schulich Notes"
exclude: [resources/shared_files]
rdiscount:
  extensions: [smart]
theme: jekyll-theme-minimal